<?= $this->extend("layout/master") ?>
<?= $this->section("head_tag") ?>
<style>
    .page-loader-overlay {
        position: fixed;
        inset: 0;
        z-index: 2000;
        background: rgba(255, 255, 255, 0.75);
        display: none;
        align-items: center;
        justify-content: center;
    }

    .versions-action-wrap .btn i {
        vertical-align: -1px;
    }
</style>
<?= $this->endSection() ?>

<?= $this->section("page_content") ?>
<div id="page_loader_overlay" class="page-loader-overlay">
    <div class="spinner-border text-primary" role="status" aria-hidden="true"></div>
</div>

<div class="page-title-box d-sm-flex align-items-center justify-content-between">
    <h5 class="mb-sm-0">Daily Reports</h5>
    <div class="page-title-right">
        <ol class="breadcrumb m-0">
            <li class="breadcrumb-item active">Reporting</li>
        </ol>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body border-bottom-dashed border-bottom">
                <div class="row justify-content-end g-2">
                    <div class="col-lg-7 col-md-7 col-sm-12">
                        <select class="form-control" id="client_dropdown_list">
                            <option value="">SELECT CLIENT ID</option>
                            <?php foreach (($clients ?? []) as $client): ?>
                                <option value="<?= (int) $client->id ?>"><?= esc($client->internal_mrn . ' - ' . $client->name()) ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="col-lg-5 col-md-5 col-sm-12 align-self-end">
                        <div class="gap-2 float-end">
                            <button type="button" id="search" class="btn btn-info bg-gradient waves-effect waves-light btn-label right" title="Search by filters"><i class="ri-search-line label-icon align-middle fs-16 ms-2"></i>Search</button>
                            <button type="button" id="clear_search" class="btn btn-success btn-icon waves-effect waves-light" title="Clear Filters"><i class="ri-eraser-line"></i></button>
                            <div class="btn-group mt-4 mt-md-0" role="group" aria-label="Basic example">
                                <button type="button" class="btn btn-warning bg-gradient waves-effect waves-light" id="back" title="Previous client"><i class="ri-arrow-left-line"></i></button>&nbsp;
                                <button type="button" class="btn btn-warning bg-gradient waves-effect waves-light" id="next" title="Next client"><i class="ri-arrow-right-line"></i></button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="card-body border-bottom-dashed border-bottom">
                <div class="table-responsive">
                    <table id="daily_report_datatable" class="table table-bordered align-middle nowrap" style="width:100%">
                        <thead>
                            <tr>
                                <th>Date</th>
                                <th>Latest Version</th>
                                <th>Status</th>
                                <th>Generated At</th>
                                <th>Generated By</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<?= $this->endSection() ?>

<?= $this->section("page_modal") ?>
<div class="modal fade" id="versions_modal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-header bg-light p-3">
                <h5 class="modal-title" id="versions_modal_title">Report Versions</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="table-responsive">
                    <table class="table table-bordered align-middle" id="versions_table">
                        <thead>
                            <tr>
                                <th>Version</th>
                                <th>Status</th>
                                <th>Generated At</th>
                                <th>Generated By</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><i class="ri-close-line align-bottom me-1"></i>Close</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="generate_report_modal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header bg-light p-3">
                <h5 class="modal-title">Generate Draft</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="mb-3">
                    <label class="form-label" for="generate_report_date">Report Date *</label>
                    <input type="text" class="form-control" id="generate_report_date" placeholder="Select Date">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><i class="ri-close-line align-bottom me-1"></i>Close</button>
                <button type="button" class="btn btn-primary" id="btn_confirm_generate"><i class="ri-file-add-line align-bottom me-1"></i>Continue</button>
            </div>
        </div>
    </div>
</div>
<?= $this->endSection() ?>

<?= $this->section("page_js") ?>
<script>
    $(document).ready(function() {
        var canGenerateReport = <?= auth()->user()->can('reporting.daily.generate') ? 'true' : 'false' ?>;
        var canDeleteVersion = <?= auth()->user()->can('reporting.daily.delete-version') ? 'true' : 'false' ?>;
        var canDeleteAll = <?= auth()->user()->can('reporting.daily.delete-all') ? 'true' : 'false' ?>;
        var csrfToken = "<?= csrf_hash() ?>";
        $.ajaxSetup({ headers: { 'X-CSRF-TOKEN': csrfToken } });
        var table = null;
        var stateTokenUrl = '<?= base_url('reports/daily/state-token') ?>';
        var initialListState = <?= json_encode($initial_state ?? ['client_id' => '', 'start_date' => '', 'end_date' => '', 'dt_page' => 0], JSON_UNESCAPED_UNICODE) ?>;
        var loaderCounter = 0;
        var activeVersionsReportId = 0;
        var activeVersionsDateLabel = '';
        var activeVersionsReportDate = '';

        function showPageLoader() {
            loaderCounter++;
            $('#page_loader_overlay').css('display', 'flex');
        }

        function hidePageLoader() {
            loaderCounter = Math.max(0, loaderCounter - 1);
            if (loaderCounter === 0) {
                $('#page_loader_overlay').hide();
            }
        }

        function toServerDate(value, selector) {
            if (selector) {
                var input = document.querySelector(selector);
                if (input && input._flatpickr && input._flatpickr.selectedDates && input._flatpickr.selectedDates.length > 0) {
                    return moment(input._flatpickr.selectedDates[0]).format('YYYY-MM-DD');
                }
            }

            if (!value) return '';
            var parsed = moment(value, [momentDateFormat, 'YYYY-MM-DD', 'DD-MM-YYYY', 'MM-DD-YYYY'], true);
            if (!parsed.isValid()) return '';
            return parsed.format('YYYY-MM-DD');
        }

        function collectCurrentListState() {
            var clientId = $('#client_dropdown_list').val() || '';
            var startDate = '';
            var endDate = '';
            var dtPage = table ? table.page() : 0;

            return {
                client_id: clientId,
                start_date: startDate || '',
                end_date: endDate || '',
                dt_page: Number.isFinite(dtPage) && dtPage > 0 ? dtPage : 0
            };
        }

        function buildStateTokenQuery(state) {
            return $.post(stateTokenUrl, state).then(function(response) {
                if (!response || response.status !== 'success') {
                    return '';
                }
                return (response.data && response.data.state_query) ? String(response.data.state_query) : '';
            }, function() {
                return '';
            });
        }

        function buildRawStateQuery(state) {
            var params = [];
            if (state.client_id) params.push('client_id=' + encodeURIComponent(state.client_id));
            if (state.start_date) params.push('start_date=' + encodeURIComponent(state.start_date));
            if (state.end_date) params.push('end_date=' + encodeURIComponent(state.end_date));
            if (Number.isFinite(state.dt_page) && state.dt_page > 0) {
                params.push('dt_page=' + encodeURIComponent(String(state.dt_page)));
            }
            return params.join('&');
        }

        function withCurrentListState(url) {
            var state = collectCurrentListState();
            return buildStateTokenQuery(state).then(function(stateQuery) {
                var tokenSuffix = stateQuery ? stateQuery.replace(/^\?/, '') : '';
                var rawSuffix = buildRawStateQuery(state);
                var suffix = tokenSuffix;
                if (rawSuffix) {
                    suffix = suffix ? (suffix + '&' + rawSuffix) : rawSuffix;
                }
                if (!suffix) return url;
                return url + (url.indexOf('?') === -1 ? '?' : '&') + suffix;
            }, function() {
                var rawSuffix = buildRawStateQuery(state);
                if (!rawSuffix) return url;
                return url + (url.indexOf('?') === -1 ? '?' : '&') + rawSuffix;
            });
        }

        function openDraft(versionId) {
            if (!versionId) return;
            var draftUrl = '<?= base_url('reports/daily/version') ?>/' + versionId + '/draft';
            withCurrentListState(draftUrl).then(function(nextUrl) {
                window.location.href = nextUrl;
            });
        }

        function handleActiveDraftResponse(response) {
            var data = response && response.data ? response.data : {};
            var draftUrl = data.draft_url || '';
            var draftDate = data.report_date || '';
            var versionNo = data.version_no || '';
            Swal.fire({
                title: 'Active Draft Exists',
                text: 'An active Daily Report draft already exists' + (draftDate ? (' for ' + draftDate) : '') + (versionNo ? (' (v' + versionNo + ')') : '') + '. Open it now?',
                icon: 'info',
                showCancelButton: true,
                confirmButtonText: 'Open Draft',
                cancelButtonText: 'Close',
                customClass: {
                    confirmButton: 'btn btn-primary w-xs me-2 mt-2',
                    cancelButton: 'btn btn-secondary w-xs mt-2'
                },
                buttonsStyling: false
            }).then(function(result) {
                if (result.isConfirmed && draftUrl) {
                    withCurrentListState(draftUrl).then(function(nextUrl) {
                        window.location.href = nextUrl;
                    });
                }
            });
        }

        $('#client_dropdown_list').select2();
        flatpickr('#generate_report_date', {
            dateFormat: dateFormat,
            weekNumbers: true,
            maxDate: 'today'
        });

        var buttonsConfig = [
            {
                extend: 'pageLength',
                className: 'btn btn-light bg-gradient waves-effect waves-light'
            },
            {
                extend: 'copy',
                className: 'btn btn-light bg-gradient waves-effect waves-light'
            },
            {
                extend: 'excel',
                className: 'btn btn-light bg-gradient waves-effect waves-light'
            },
            {
                extend: 'colvis',
                className: 'btn btn-light bg-gradient waves-effect waves-light'
            }
        ];

        if (canGenerateReport) {
            buttonsConfig.unshift({
                text: '<i class="ri-file-add-line align-bottom me-1"></i>Generate Draft',
                className: 'btn btn-soft-info waves-effect waves-light material-shadow-none',
                attr: {
                    id: 'btn_generate_report'
                },
                action: function() {
                    startGenerate('');
                }
            });
        }

        table = $('#daily_report_datatable').DataTable({
            ajax: {
                url: '<?= base_url('reports/daily/data') ?>',
                type: 'POST',
                data: function(d) {
                    d.subject_id = $('#client_dropdown_list').val();
                    d.start_date = '';
                    d.end_date = '';
                },
                dataSrc: function(json) {
                    return (json && json.data) ? json.data : [];
                }
            },
            lengthChange: false,
            layout: {
                topStart: {
                    buttons: buttonsConfig
                },
                topEnd: {
                    search: {
                        placeholder: 'Search'
                    }
                }
            },
            order: [[0, 'desc']],
            columns: [
                {
                    data: 'report_date',
                    render: function(data, type, row) {
                        if (!data) return '';
                        if (type === 'sort' || type === 'type') {
                            return moment(data, 'YYYY-MM-DD').format('YYYYMMDD');
                        }
                        return row.report_date_display || moment(data, 'YYYY-MM-DD').format(momentDateFormat);
                    }
                },
                {
                    data: null,
                    render: function(data, type, row) {
                        return row.latest_version_id ? ('v' + row.latest_version_no) : '-';
                    }
                },
                {
                    data: 'latest_status',
                    render: function(data) {
                        if (String(data || '').toUpperCase() === 'FINAL') {
                            return '<span class="badge bg-success-subtle text-success text-uppercase">Final</span>';
                        }
                        return '<span class="badge bg-warning-subtle text-warning text-uppercase">Draft</span>';
                    }
                },
                {
                    data: 'generated_at',
                    defaultContent: '',
                    render: function(data, type, row) {
                        if (!data) return '';
                        if (type === 'sort' || type === 'type') {
                            return moment(data).format('YYYYMMDDHHmmss');
                        }
                        return row.generated_at_display || moment(data).format(momentDateFormat + ' HH:mm:ss');
                    }
                },
                {
                    data: 'generated_by_name',
                    defaultContent: '',
                    render: function(data) {
                        return data || '-';
                    }
                },
                {
                    data: null,
                    orderable: false,
                    render: function(data, type, row) {
                        var menu = '<div class="dropdown d-inline-block float-end">';
                        menu += '<a class="btn btn-soft-secondary btn-sm" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="ri-settings-3-fill align-middle"></i></a>';
                        menu += '<ul class="dropdown-menu dropdown-menu-end">';

                        if (canGenerateReport) {
                            if (!row.report_id) {
                                menu += '<li><a class="dropdown-item generate-report" href="#" data-date="' + (row.report_date || '') + '"><i class="ri-file-add-line align-bottom me-2 text-muted"></i>Generate Draft</a></li>';
                            } else if (row.latest_status === 'DRAFT' && row.latest_version_id) {
                                menu += '<li><a class="dropdown-item open-draft-link" href="#" data-version-id="' + row.latest_version_id + '"><i class="ri-draft-line align-bottom me-2 text-muted"></i>Open Active Draft</a></li>';
                            } else if (row.latest_status === 'FINAL') {
                                menu += '<li><a class="dropdown-item regenerate-version" href="#" data-version-id="' + row.latest_version_id + '" data-report-date="' + (row.report_date || '') + '"><i class="ri-refresh-line align-bottom me-2 text-muted"></i>Regenerate Draft</a></li>';
                            }
                        }

                        if (row.report_id) {
                            menu += '<li><a class="dropdown-item versions" href="#" data-report-id="' + row.report_id + '" data-date-display="' + (row.report_date_display || row.report_date || '') + '" data-report-date="' + (row.report_date || '') + '"><i class="ri-history-line align-bottom me-2 text-muted"></i>View Versions</a></li>';
                        }

                        if (row.latest_version_id && row.latest_status === 'FINAL' && row.latest_artifact_id) {
                            menu += '<li><a class="dropdown-item" target="_blank" href="<?= base_url('reports/daily/version') ?>/' + row.latest_version_id + '/pdf"><i class="ri-file-pdf-line align-bottom me-2 text-muted"></i>View Latest PDF</a></li>';
                        }

                        if (canDeleteVersion && row.latest_version_id) {
                            menu += '<li><a class="dropdown-item delete-latest-version" href="#" data-version-id="' + row.latest_version_id + '" data-report-id="' + row.report_id + '" data-version-label="v' + row.latest_version_no + '" data-version-status="' + row.latest_status + '"><i class="ri-delete-bin-line align-bottom me-2 text-muted"></i>Delete Latest Version</a></li>';
                        }

                        if (canDeleteAll && row.report_id) {
                            menu += '<li><a class="dropdown-item text-danger delete-all-versions" href="#" data-report-id="' + row.report_id + '"><i class="ri-delete-bin-6-line align-bottom me-2 text-danger"></i>Delete All Versions</a></li>';
                        }

                        menu += '</ul></div>';
                        return menu;
                    }
                }
            ]
        });

        function validateSelection() {
            var clientId = $('#client_dropdown_list').val();
            if (!clientId) {
                showAlert('', 'Select Client', 'error');
                return false;
            }
            return true;
        }

        function reloadTableWithLoader(resetPaging) {
            showPageLoader();
            table.ajax.reload(function() {
                hidePageLoader();
            }, resetPaging);
        }

        function postWithLoader(url, payload) {
            showPageLoader();
            return $.post(url, payload).always(function() {
                hidePageLoader();
            });
        }

        function runGenerate(clientId, reportDate) {
            postWithLoader('<?= base_url('reports/daily/generate') ?>', {
                subject_id: clientId,
                report_date: reportDate
            }).done(function(response) {
                if (response.status !== 'success') {
                    if (response.statusText === 'ActiveDraftExists') {
                        handleActiveDraftResponse(response);
                        return;
                    }
                    showAlert(response.statusText || '', response.message || 'Unable to generate draft.', response.status || 'error');
                    return;
                }

                $('#generate_report_modal').modal('hide');
                showAlert(response.statusText, response.message, response.status);
                reloadTableWithLoader(false);
                if (response.data && response.data.draft_url) {
                    withCurrentListState(response.data.draft_url).then(function(nextUrl) {
                        window.location.href = nextUrl;
                    });
                }
            }).fail(function(jqXHR, textStatus, error) {
                showAlert(jqXHR.status, 'Request failed: ' + textStatus + '<br>' + error, 'error');
            });
        }

        function runRegenerate(versionId) {
            postWithLoader('<?= base_url('reports/daily/version') ?>/' + versionId + '/regenerate', {})
                .done(function(response) {
                    if (response.status !== 'success') {
                        if (response.statusText === 'ActiveDraftExists') {
                            handleActiveDraftResponse(response);
                            return;
                        }
                        showAlert(response.statusText || '', response.message || 'Unable to regenerate draft.', response.status || 'error');
                        return;
                    }

                    showAlert(response.statusText || '', response.message || 'Draft regenerated.', response.status || 'success');
                    reloadTableWithLoader(false);
                    if (response.data && response.data.draft_url) {
                        withCurrentListState(response.data.draft_url).then(function(nextUrl) {
                            window.location.href = nextUrl;
                        });
                    }
                })
                .fail(function(jqXHR, textStatus, error) {
                    showAlert(jqXHR.status, 'Request failed: ' + textStatus + '<br>' + error, 'error');
                });
        }

        function startGenerate(reportDatePrefill) {
            if (!validateSelection()) return;
            $('#generate_report_date').val('');
            if (reportDatePrefill) {
                $('#generate_report_date').val(moment(reportDatePrefill, 'YYYY-MM-DD').format(momentDateFormat));
            }
            $('#generate_report_modal').modal('show');
        }

        function checkAndGenerate(clientId, reportDate) {
            postWithLoader('<?= base_url('reports/daily/check-generate') ?>', {
                subject_id: clientId,
                report_date: reportDate
            }).done(function(check) {
                if (check.status === 'error' && check.statusText === 'NoSession') {
                    $('#generate_report_modal').modal('hide');
                    Swal.fire({
                        title: 'No Sessions',
                        text: 'No session exists for selected date.',
                        icon: 'info',
                        customClass: {
                            confirmButton: 'btn btn-primary w-xs me-2 mt-2'
                        },
                        buttonsStyling: false
                    });
                    return;
                }

                if (check.status === 'error' && check.statusText === 'ActiveDraftExists') {
                    $('#generate_report_modal').modal('hide');
                    handleActiveDraftResponse(check);
                    return;
                }

                if (check.status !== 'success') {
                    showAlert(check.statusText || '', check.message || 'Generate check failed.', check.status || 'error');
                    return;
                }

                if (check.data && check.data.report_exists) {
                    Swal.fire({
                        title: 'Daily Report Exists',
                        text: 'Latest version is v' + check.data.latest_version_no + '. Create the next draft version?',
                        icon: 'warning',
                        showCancelButton: true,
                        confirmButtonText: 'Create Draft',
                        cancelButtonText: 'Cancel',
                        customClass: {
                            confirmButton: 'btn btn-primary w-xs me-2 mt-2',
                            cancelButton: 'btn btn-secondary w-xs mt-2'
                        },
                        buttonsStyling: false
                    }).then(function(result) {
                        if (result.isConfirmed) {
                            runGenerate(clientId, reportDate);
                        }
                    });
                    return;
                }

                runGenerate(clientId, reportDate);
            }).fail(function(jqXHR, textStatus, error) {
                showAlert(jqXHR.status, 'Request failed: ' + textStatus + '<br>' + error, 'error');
            });
        }

        function runDeleteLatest(versionId, reportId) {
            if (!versionId) return;
            postWithLoader('<?= base_url('reports/daily/version') ?>/' + versionId + '/delete', {})
                .done(function(response) {
                    if (response.status !== 'success') {
                        showAlert(response.statusText || '', response.message || 'Unable to delete latest version.', response.status || 'error');
                        return;
                    }

                    showAlert(response.statusText || '', response.message || 'Deleted.', response.status || 'success');
                    reloadTableWithLoader(false);

                    var reportDeleted = response.data && response.data.report_deleted;
                    if (reportDeleted) {
                        activeVersionsReportId = 0;
                        activeVersionsDateLabel = '';
                        $('#versions_modal').modal('hide');
                        return;
                    }

                    if (activeVersionsReportId && reportId && activeVersionsReportId === reportId && $('#versions_modal').hasClass('show')) {
                        loadVersions(activeVersionsReportId, activeVersionsDateLabel);
                    }
                })
                .fail(function(jqXHR, textStatus, error) {
                    showAlert(jqXHR.status, 'Request failed: ' + textStatus + '<br>' + error, 'error');
                });
        }

        function runDeleteAll(reportId) {
            if (!reportId) return;
            postWithLoader('<?= base_url('reports/daily/report') ?>/' + reportId + '/delete-all', {})
                .done(function(response) {
                    if (response.status !== 'success') {
                        showAlert(response.statusText || '', response.message || 'Unable to delete all versions.', response.status || 'error');
                        return;
                    }

                    showAlert(response.statusText || '', response.message || 'Deleted.', response.status || 'success');
                    activeVersionsReportId = 0;
                    activeVersionsDateLabel = '';
                    $('#versions_modal').modal('hide');
                    reloadTableWithLoader(false);
                })
                .fail(function(jqXHR, textStatus, error) {
                    showAlert(jqXHR.status, 'Request failed: ' + textStatus + '<br>' + error, 'error');
                });
        }

        function loadVersions(reportId, dateLabel, reportDate) {
            activeVersionsReportId = parseInt(reportId, 10) || 0;
            activeVersionsDateLabel = dateLabel || '';
            activeVersionsReportDate = reportDate || '';
            $('#versions_modal_title').text('Report Versions [' + activeVersionsDateLabel + ']');

            postWithLoader('<?= base_url('reports/daily/versions') ?>', { report_id: activeVersionsReportId })
                .done(function(response) {
                    if (response.status !== 'success') {
                        showAlert(response.statusText, response.message, response.status);
                        return;
                    }

                    var rows = response.data || [];
                    var html = '';
                    rows.forEach(function(row, idx) {
                        var isLatest = idx === 0;
                        var actionParts = [];

                        if (row.status === 'DRAFT') {
                            actionParts.push('<a class="btn btn-sm btn-soft-primary open-draft-link" href="#" data-version-id="' + row.version_id + '"><i class="ri-draft-line me-1"></i>Open Draft</a>');
                        } else if (row.status === 'FINAL' && row.artifact_id) {
                            actionParts.push('<a target="_blank" class="btn btn-sm btn-soft-danger" href="<?= base_url('reports/daily/version') ?>/' + row.version_id + '/pdf"><i class="ri-file-pdf-line me-1"></i>View PDF</a>');
                        }

                        if (row.status === 'FINAL' && canGenerateReport) {
                            actionParts.push('<button type="button" class="btn btn-sm btn-soft-info regenerate-version" data-version-id="' + row.version_id + '" data-report-date="' + activeVersionsReportDate + '"><i class="ri-refresh-line me-1"></i>Regenerate</button>');
                        }

                        if (canDeleteVersion && isLatest) {
                            actionParts.push('<button type="button" class="btn btn-sm btn-soft-danger delete-latest-version" data-version-id="' + row.version_id + '" data-report-id="' + activeVersionsReportId + '" data-version-label="v' + row.version_no + '" data-version-status="' + row.status + '"><i class="ri-delete-bin-line me-1"></i>Delete</button>');
                        }

                        var actionHtml = actionParts.length > 0
                            ? '<div class="versions-action-wrap d-flex flex-wrap gap-1">' + actionParts.join('') + '</div>'
                            : '-';

                        html += '<tr>' +
                            '<td>v' + row.version_no + '</td>' +
                            '<td>' + row.status + '</td>' +
                            '<td>' + (row.generated_at_display || row.generated_at || '-') + '</td>' +
                            '<td>' + (row.generated_by_name || '-') + '</td>' +
                            '<td>' + actionHtml + '</td>' +
                            '</tr>';
                    });

                    if (html === '') {
                        html = '<tr><td colspan="5" class="text-center">No versions found.</td></tr>';
                    }

                    $('#versions_table tbody').html(html);
                    $('#versions_modal').modal('show');
                })
                .fail(function(jqXHR, textStatus, error) {
                    showAlert(jqXHR.status, 'Request failed: ' + textStatus + '<br>' + error, 'error');
                });
        }

        $('#daily_report_datatable').on('click', '.generate-report', function(e) {
            e.preventDefault();
            if (!canGenerateReport) return;
            startGenerate($(this).data('date') || '');
        });

        $('#btn_confirm_generate').on('click', function() {
            if (!canGenerateReport) return;
            if (!validateSelection()) return;
            var clientId = $('#client_dropdown_list').val();
            var selected = $('#generate_report_date').val();
            if (!selected) {
                showAlert('', 'Report date is required.', 'error');
                return;
            }

            var reportDate = toServerDate(selected, '#generate_report_date');
            if (!reportDate) {
                showAlert('', 'Invalid report date.', 'error');
                return;
            }

            checkAndGenerate(clientId, reportDate);
        });

        $('#daily_report_datatable').on('click', '.versions', function(e) {
            e.preventDefault();
            loadVersions($(this).data('report-id'), $(this).data('date-display') || '', $(this).data('report-date') || '');
        });

        $('#daily_report_datatable, #versions_table').on('click', '.open-draft-link', function(e) {
            e.preventDefault();
            openDraft(parseInt($(this).data('version-id'), 10) || 0);
        });

        $('#daily_report_datatable, #versions_table').on('click', '.regenerate-version', function(e) {
            e.preventDefault();
            if (!canGenerateReport) return;
            var versionId = parseInt($(this).data('version-id'), 10) || 0;
            if (!versionId) {
                showAlert('', 'Version is required to regenerate.', 'error');
                return;
            }

            Swal.fire({
                title: 'Regenerate Draft',
                text: 'This will create a new draft version for the same daily report date.',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonText: '<i class="ri-refresh-line align-bottom me-1"></i>Regenerate',
                cancelButtonText: '<i class="ri-close-line align-bottom me-1"></i>Cancel',
                customClass: {
                    confirmButton: 'btn btn-primary w-xs me-2 mt-2',
                    cancelButton: 'btn btn-secondary w-xs mt-2'
                },
                buttonsStyling: false
            }).then(function(result) {
                if (!result.isConfirmed) return;
                runRegenerate(versionId);
            });
        });

        $('#daily_report_datatable, #versions_table').on('click', '.delete-latest-version', function(e) {
            e.preventDefault();
            if (!canDeleteVersion) return;

            var versionId = parseInt($(this).data('version-id'), 10) || 0;
            var reportId = parseInt($(this).data('report-id'), 10) || 0;
            var versionLabel = $(this).data('version-label') || ('v' + versionId);
            var versionStatus = ($(this).data('version-status') || '').toString().toUpperCase();
            if (!versionId) return;

            Swal.fire({
                title: 'Delete Latest Version',
                text: 'Delete ' + versionLabel + ' (' + (versionStatus || 'DRAFT') + ')? You can only delete the latest version.',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonText: '<i class="ri-delete-bin-line align-bottom me-1"></i>Delete',
                cancelButtonText: '<i class="ri-close-line align-bottom me-1"></i>Cancel',
                customClass: {
                    confirmButton: 'btn btn-danger w-xs me-2 mt-2',
                    cancelButton: 'btn btn-secondary w-xs mt-2'
                },
                buttonsStyling: false
            }).then(function(result) {
                if (!result.isConfirmed) return;
                runDeleteLatest(versionId, reportId);
            });
        });

        $('#daily_report_datatable').on('click', '.delete-all-versions', function(e) {
            e.preventDefault();
            if (!canDeleteAll) return;

            var reportId = parseInt($(this).data('report-id'), 10) || 0;
            if (!reportId) return;

            Swal.fire({
                title: 'Delete All Versions',
                text: 'This will permanently delete all versions and related PDF/media files for this report.',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonText: '<i class="ri-delete-bin-6-line align-bottom me-1"></i>Delete All',
                cancelButtonText: '<i class="ri-close-line align-bottom me-1"></i>Cancel',
                customClass: {
                    confirmButton: 'btn btn-danger w-xs me-2 mt-2',
                    cancelButton: 'btn btn-secondary w-xs mt-2'
                },
                buttonsStyling: false
            }).then(function(result) {
                if (!result.isConfirmed) return;
                runDeleteAll(reportId);
            });
        });

        $('#search').on('click', function() {
            if (!validateSelection()) return;
            reloadTableWithLoader(true);
        });

        $('#clear_search').on('click', function() {
            $('#client_dropdown_list').val('').change();
            table.clear().draw();
        });

        $('#client_dropdown_list').on('change', function() {
            table.clear().draw();
        });

        $('#back').on('click', function() {
            var dropdown = $('#client_dropdown_list');
            var selectedIndex = dropdown.prop('selectedIndex');
            if (selectedIndex > 1) {
                dropdown.prop('selectedIndex', selectedIndex - 1).trigger('change');
            }
            reloadTableWithLoader(true);
        });

        $('#next').on('click', function() {
            var dropdown = $('#client_dropdown_list');
            var selectedIndex = dropdown.prop('selectedIndex');
            var optionsCount = dropdown.find('option').length;
            if (selectedIndex + 1 < optionsCount) {
                dropdown.prop('selectedIndex', selectedIndex + 1).trigger('change');
            }
            reloadTableWithLoader(true);
        });

        var restoredState = initialListState || {};
        if (restoredState.client_id) {
            $('#client_dropdown_list').val(restoredState.client_id).trigger('change');

            showPageLoader();
            table.ajax.reload(function() {
                if (restoredState.dt_page > 0) {
                    var pageInfo = table.page.info();
                    var maxPage = Math.max(0, pageInfo.pages - 1);
                    table.page(Math.min(restoredState.dt_page, maxPage)).draw('page');
                }
                hidePageLoader();
            }, false);
        }
    });
</script>
<?= $this->endSection() ?>
