<?= $this->extend("layout/master-profile") ?>
<?= $this->section("head_tag") ?>
<style>
    .daily-report-page {
        position: relative;
        min-height: 220px;
    }

    .page-loader-overlay {
        position: absolute;
        inset: 0;
        z-index: 10;
        background: rgba(255, 255, 255, 0.75);
        display: none;
        align-items: center;
        justify-content: center;
    }

    .flatpickr-calendar.open { z-index: 9999 !important; }
</style>
<?= $this->endSection() ?>

<?= $this->section("page_content") ?>
<div class="mx-n3 pt-2 px-2 daily-report-page">
    <div id="page_loader_overlay" class="page-loader-overlay">
        <div class="spinner-border text-primary" role="status" aria-hidden="true"></div>
    </div>
    <div class="table-responsive">
        <table id="daily_report_datatable" class="table table-bordered align-middle nowrap" style="width:100%">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Latest Version</th>
                    <th>Status</th>
                    <th>Generated At</th>
                    <th>Generated By</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>
<?= $this->endSection() ?>

<?= $this->section("page_modal") ?>
<div class="modal fade" id="versions_modal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-header bg-light p-3">
                <h5 class="modal-title" id="versions_modal_title">Report Versions</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="table-responsive">
                    <table class="table table-bordered align-middle" id="versions_table">
                        <thead>
                            <tr>
                                <th>Version</th>
                                <th>Status</th>
                                <th>Generated At</th>
                                <th>Generated By</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><i class="ri-close-line align-bottom me-1"></i>Close</button>
            </div>
        </div>
    </div>
</div>

<?= $this->endSection() ?>

<?= $this->section("page_js") ?>
<script>
    $(document).ready(function() {
        var canGenerateReport = <?= auth()->user()->can('client-profile.reports.daily.generate') ? 'true' : 'false' ?>;
        var canRegenerate = <?= auth()->user()->can('client-profile.reports.daily.regenerate') ? 'true' : 'false' ?>;
        var canDeleteVersion = <?= auth()->user()->can('client-profile.reports.daily.delete-version') ? 'true' : 'false' ?>;
        var canDeleteAll = <?= auth()->user()->can('client-profile.reports.daily.delete-all') ? 'true' : 'false' ?>;
        var encodedClientId = '<?= esc($encodedClientId ?? '', 'js') ?>';
        var subjectId = <?= (int) ($client->id ?? 0) ?>;
        var csrfToken = "<?= csrf_hash() ?>";
        $.ajaxSetup({ headers: { 'X-CSRF-TOKEN': csrfToken } });

        var baseUrl = '<?= base_url('client-profile/reports/daily') ?>/' + encodedClientId;

        function showPageLoader() {
            $('#page_loader_overlay').css('display', 'flex');
        }

        function hidePageLoader() {
            $('#page_loader_overlay').hide();
        }

        function postWithLoader(url, payload) {
            showPageLoader();
            return $.post(url, payload).always(function() {
                hidePageLoader();
            });
        }

        function openDraft(versionId) {
            window.location.href = baseUrl + '/version/' + versionId + '/draft';
        }

        function handleCheckGenerateResult(reportDate, result) {
            if (result.status === 'success') {
                Swal.fire({
                    title: 'Generate Daily Report',
                    text: result.message || 'Generate draft for ' + reportDate + '?',
                    icon: 'question',
                    showCancelButton: true,
                    confirmButtonText: 'Generate',
                    cancelButtonText: 'Cancel',
                    customClass: { confirmButton: 'btn btn-primary w-xs me-2 mt-2', cancelButton: 'btn btn-secondary w-xs mt-2' },
                    buttonsStyling: false
                }).then(function(res) {
                    if (res.isConfirmed) {
                        doGenerate(reportDate);
                    }
                });
            } else if (result.statusText === 'ActiveDraftExists') {
                var draftUrl = (result.data && result.data.draft_url) ? result.data.draft_url : '';
                Swal.fire({
                    title: 'Active Draft Exists',
                    text: result.message || 'An active draft already exists for this date.',
                    icon: 'info',
                    showCancelButton: true,
                    confirmButtonText: 'Open Draft',
                    cancelButtonText: 'Cancel',
                    customClass: { confirmButton: 'btn btn-primary w-xs me-2 mt-2', cancelButton: 'btn btn-secondary w-xs mt-2' },
                    buttonsStyling: false
                }).then(function(res) {
                    if (res.isConfirmed && draftUrl) {
                        window.location.href = draftUrl;
                    }
                });
            } else if (result.statusText === 'NoSession') {
                showAlert('No Sessions', result.message || 'No session exists for the selected date.', 'warning');
            } else {
                showAlert(result.statusText, result.message || 'Cannot generate report.', 'error');
            }
        }

        function doGenerate(reportDate) {
            showPageLoader();
            $.post(baseUrl + '/generate', { report_date: reportDate })
                .done(function(result) {
                    hidePageLoader();
                    if (result.status === 'success') {
                        var draftUrl = result.data && result.data.draft_url ? result.data.draft_url : '';
                        if (draftUrl) {
                            window.location.href = draftUrl;
                        } else {
                            showAlert('DailyReport', 'Draft generated successfully.', 'success');
                            table.ajax.reload();
                        }
                    } else {
                        handleCheckGenerateResult(reportDate, result);
                    }
                })
                .fail(function(jqXHR) {
                    hidePageLoader();
                    showAlert(jqXHR.status, 'Request failed.', 'error');
                });
        }

        function doRegenerate(versionId, versionLabel) {
            Swal.fire({
                title: 'Regenerate Draft',
                text: 'This will create a new draft from ' + (versionLabel || 'this version') + '. Continue?',
                icon: 'question',
                showCancelButton: true,
                confirmButtonText: 'Regenerate',
                cancelButtonText: 'Cancel',
                customClass: { confirmButton: 'btn btn-warning w-xs me-2 mt-2', cancelButton: 'btn btn-secondary w-xs mt-2' },
                buttonsStyling: false
            }).then(function(res) {
                if (!res.isConfirmed) return;
                postWithLoader(baseUrl + '/version/' + versionId + '/regenerate', {})
                    .done(function(result) {
                        if (result.status === 'success') {
                            var draftUrl = result.data && result.data.draft_url ? result.data.draft_url : '';
                            if (draftUrl) {
                                window.location.href = draftUrl;
                            } else {
                                showAlert('Regenerate', 'New draft created successfully.', 'success');
                                table.ajax.reload();
                                $('#versions_modal').modal('hide');
                            }
                        } else {
                            showAlert(result.statusText, result.message || 'Regeneration failed.', 'error');
                        }
                    })
                    .fail(function(jqXHR) {
                        showAlert(jqXHR.status, 'Request failed.', 'error');
                    });
            });
        }

        function doDeleteVersion(versionId, versionLabel) {
            Swal.fire({
                title: 'Delete Version',
                text: 'Delete ' + (versionLabel || 'this version') + '? This cannot be undone.',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Delete',
                cancelButtonText: 'Cancel',
                customClass: { confirmButton: 'btn btn-danger w-xs me-2 mt-2', cancelButton: 'btn btn-secondary w-xs mt-2' },
                buttonsStyling: false
            }).then(function(res) {
                if (!res.isConfirmed) return;
                postWithLoader(baseUrl + '/version/' + versionId + '/delete', {})
                    .done(function(result) {
                        if (result.status === 'success') {
                            table.ajax.reload();
                            $('#versions_modal').modal('hide');
                        } else {
                            showAlert(result.statusText, result.message || 'Delete failed.', 'error');
                        }
                    })
                    .fail(function(jqXHR) {
                        showAlert(jqXHR.status, 'Request failed.', 'error');
                    });
            });
        }

        function startGenerate(prefillDate) {
            var inputId = 'swal_report_date_' + Date.now();
            Swal.fire({
                title: 'Generate Daily Report',
                html: '<label class="form-label">Report Date</label><input id="' + inputId + '" type="text" class="form-control flatpickr-input" placeholder="Select date" readonly="readonly">',
                showCancelButton: true,
                confirmButtonText: 'Check & Generate',
                cancelButtonText: 'Cancel',
                customClass: { confirmButton: 'btn btn-info w-xs me-2 mt-2', cancelButton: 'btn btn-secondary w-xs mt-2' },
                buttonsStyling: false,
                didOpen: function() {
                    flatpickr('#' + inputId, { dateFormat: dateFormat, weekNumbers: true, maxDate: 'today', defaultDate: prefillDate || null });
                },
                preConfirm: function() {
                    var input = document.getElementById(inputId);
                    var fp = input && input._flatpickr ? input._flatpickr : null;
                    var reportDate = fp && fp.selectedDates && fp.selectedDates.length > 0
                        ? moment(fp.selectedDates[0]).format('YYYY-MM-DD')
                        : '';
                    if (!reportDate) {
                        Swal.showValidationMessage('Please select a date.');
                        return false;
                    }
                    return reportDate;
                }
            }).then(function(result) {
                if (!result.isConfirmed || !result.value) return;
                var reportDate = result.value;
                showPageLoader();
                $.post(baseUrl + '/check-generate', { report_date: reportDate })
                    .done(function(res) {
                        hidePageLoader();
                        handleCheckGenerateResult(reportDate, res);
                    })
                    .fail(function(jqXHR) {
                        hidePageLoader();
                        showAlert(jqXHR.status, 'Request failed.', 'error');
                    });
            });
        }

        var buttonsConfig = [
            { extend: 'pageLength', className: 'btn btn-light bg-gradient waves-effect waves-light' },
            { extend: 'copy', className: 'btn btn-light bg-gradient waves-effect waves-light' },
            { extend: 'excel', className: 'btn btn-light bg-gradient waves-effect waves-light' },
            { extend: 'colvis', className: 'btn btn-light bg-gradient waves-effect waves-light' }
        ];

        if (canGenerateReport) {
            buttonsConfig.unshift({
                text: '<i class="ri-file-add-line align-bottom me-1"></i>Generate Draft',
                className: 'btn btn-soft-info waves-effect waves-light material-shadow-none',
                action: function() { startGenerate(''); }
            });
        }

        var table = $('#daily_report_datatable').DataTable({
            ajax: {
                url: baseUrl + '/data',
                type: 'POST',
                beforeSend: function() { showPageLoader(); },
                complete: function() { hidePageLoader(); },
                error: function() { hidePageLoader(); },
                dataSrc: function(json) {
                    return (json && json.data) ? json.data : [];
                }
            },
            lengthChange: false,
            layout: {
                topStart: { buttons: buttonsConfig },
                topEnd: { search: { placeholder: 'Search' } }
            },
            order: [[0, 'desc']],
            columns: [
                {
                    data: 'report_date',
                    render: function(data, type, row) {
                        if (!data) return '';
                        if (type === 'sort' || type === 'type') {
                            return moment(data, 'YYYY-MM-DD').format('YYYYMMDD');
                        }
                        return row.report_date_display || moment(data, 'YYYY-MM-DD').format(momentDateFormat);
                    }
                },
                {
                    data: null,
                    render: function(data, type, row) {
                        return row.latest_version_id ? ('v' + row.latest_version_no) : '-';
                    }
                },
                {
                    data: 'latest_status',
                    render: function(data) {
                        var s = String(data || '').toUpperCase();
                        if (s === 'FINAL') return '<span class="badge bg-success-subtle text-success text-uppercase">Final</span>';
                        if (s === 'DRAFT') return '<span class="badge bg-warning-subtle text-warning text-uppercase">Draft</span>';
                        return '<span class="badge bg-secondary-subtle text-secondary text-uppercase">' + (data || 'N/A') + '</span>';
                    }
                },
                {
                    data: 'generated_at',
                    defaultContent: '',
                    render: function(data, type, row) {
                        if (!data) return '';
                        if (type === 'sort' || type === 'type') return moment(data).format('YYYYMMDDHHmmss');
                        return row.generated_at_display || moment(data).format(momentDateFormat + ' HH:mm:ss');
                    }
                },
                {
                    data: 'generated_by_name',
                    defaultContent: '',
                    render: function(data) { return data || '-'; }
                },
                {
                    data: null,
                    orderable: false,
                    render: function(data, type, row) {
                        var status = String(row.latest_status || 'FINAL').toUpperCase();
                        var menu = '<div class="dropdown d-inline-block float-end">';
                        menu += '<a class="btn btn-soft-secondary btn-sm" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="ri-settings-3-fill align-middle"></i></a>';
                        menu += '<ul class="dropdown-menu dropdown-menu-end">';

                        if (row.report_id) {
                            menu += '<li><a class="dropdown-item versions" href="#" data-report-id="' + row.report_id + '" data-date-display="' + (row.report_date_display || row.report_date || '') + '"><i class="ri-history-line align-bottom me-2 text-muted"></i>View Versions</a></li>';
                        }

                        if (status === 'DRAFT' && row.latest_version_id) {
                            menu += '<li><a class="dropdown-item" href="' + baseUrl + '/version/' + row.latest_version_id + '/draft"><i class="ri-edit-line align-bottom me-2 text-muted"></i>Edit Draft</a></li>';
                        }

                        if (status === 'FINAL' && row.latest_version_id && row.latest_artifact_id) {
                            menu += '<li><a class="dropdown-item" href="' + baseUrl + '/version/' + row.latest_version_id + '/pdf"><i class="ri-download-2-line align-bottom me-2 text-muted"></i>Download Latest Version</a></li>';
                        }

                        if (status === 'FINAL' && row.latest_version_id && canRegenerate) {
                            menu += '<li><a class="dropdown-item regenerate-version" href="#" data-version-id="' + row.latest_version_id + '" data-version-label="v' + row.latest_version_no + '"><i class="ri-restart-line align-bottom me-2 text-muted"></i>Regenerate Draft</a></li>';
                        }

                        if (canDeleteVersion && row.latest_version_id) {
                            menu += '<li><a class="dropdown-item delete-latest-version" href="#" data-version-id="' + row.latest_version_id + '" data-version-label="v' + row.latest_version_no + '"><i class="ri-delete-bin-line align-bottom me-2 text-warning"></i>Delete Latest Version</a></li>';
                        }

                        if (canDeleteAll && row.report_id) {
                            menu += '<li><hr class="dropdown-divider"></li>';
                            menu += '<li><a class="dropdown-item text-danger delete-all" href="#" data-report-id="' + row.report_id + '" data-date-display="' + (row.report_date_display || row.report_date || '') + '"><i class="ri-delete-bin-line align-bottom me-2"></i>Delete All Versions</a></li>';
                        }

                        menu += '</ul></div>';
                        return menu;
                    }
                }
            ]
        });

        function loadVersions(reportId, dateLabel) {
            $('#versions_modal_title').text('Report Versions [' + (dateLabel || '') + ']');

            postWithLoader(baseUrl + '/versions', { report_id: reportId })
                .done(function(response) {
                    if (response.status !== 'success') {
                        showAlert(response.statusText, response.message, response.status);
                        return;
                    }

                    var rows = response.data || [];
                    var maxVersionNo = rows.reduce(function(m, r) { return Math.max(m, r.version_no || 0); }, 0);
                    var html = '';
                    rows.forEach(function(row) {
                        var status = String(row.status || 'FINAL').toUpperCase();
                        var isLatest = (row.version_no === maxVersionNo);
                        var statusBadge = status === 'FINAL'
                            ? '<span class="badge bg-success-subtle text-success">Final</span>'
                            : '<span class="badge bg-warning-subtle text-warning">Draft</span>';

                        var actionBtn = '';
                        if (status === 'DRAFT') {
                            actionBtn = '<a class="btn btn-sm btn-light" href="' + baseUrl + '/version/' + row.version_id + '/draft">Edit Draft</a>';
                        } else if (row.artifact_id) {
                            actionBtn = '<a class="btn btn-sm btn-light" href="' + baseUrl + '/version/' + row.version_id + '/pdf">Download PDF</a>';
                        } else {
                            actionBtn = '<button class="btn btn-sm btn-light" disabled>No PDF</button>';
                        }
                        if (status === 'FINAL' && canRegenerate) {
                            actionBtn += ' <a class="btn btn-sm btn-warning regenerate-version" href="#" data-version-id="' + row.version_id + '" data-version-label="v' + row.version_no + '">Regenerate</a>';
                        }
                        if (canDeleteVersion && isLatest) {
                            actionBtn += ' <a class="btn btn-sm btn-danger delete-latest-version" href="#" data-version-id="' + row.version_id + '" data-version-label="v' + row.version_no + '">Delete</a>';
                        }

                        html += '<tr>' +
                            '<td>v' + row.version_no + '</td>' +
                            '<td>' + statusBadge + '</td>' +
                            '<td>' + (row.generated_at_display || row.generated_at || '-') + '</td>' +
                            '<td>' + (row.generated_by_name || '-') + '</td>' +
                            '<td>' + actionBtn + '</td>' +
                            '</tr>';
                    });

                    if (html === '') {
                        html = '<tr><td colspan="5" class="text-center">No versions found.</td></tr>';
                    }

                    $('#versions_table tbody').html(html);
                    $('#versions_modal').modal('show');
                })
                .fail(function(jqXHR, textStatus, error) {
                    showAlert(jqXHR.status, 'Request failed: ' + textStatus + '<br>' + error, 'error');
                });
        }

        $('#daily_report_datatable').on('click', '.versions', function(e) {
            e.preventDefault();
            loadVersions($(this).data('report-id'), $(this).data('date-display') || '');
        });

        $('#daily_report_datatable, #versions_table').on('click', '.regenerate-version', function(e) {
            e.preventDefault();
            doRegenerate($(this).data('version-id'), $(this).data('version-label'));
        });

        $('#daily_report_datatable, #versions_table').on('click', '.delete-latest-version', function(e) {
            e.preventDefault();
            doDeleteVersion($(this).data('version-id'), $(this).data('version-label'));
        });

        $('#daily_report_datatable').on('click', '.delete-all', function(e) {
            e.preventDefault();
            var reportId = $(this).data('report-id');
            var dateLabel = $(this).data('date-display') || '';
            Swal.fire({
                title: 'Delete All Versions',
                text: 'Delete all versions for ' + (dateLabel || 'this report') + '? This cannot be undone.',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Delete',
                cancelButtonText: 'Cancel',
                customClass: { confirmButton: 'btn btn-danger w-xs me-2 mt-2', cancelButton: 'btn btn-secondary w-xs mt-2' },
                buttonsStyling: false
            }).then(function(res) {
                if (!res.isConfirmed) return;
                postWithLoader(baseUrl + '/report/' + reportId + '/delete-all', {})
                    .done(function(result) {
                        if (result.status === 'success') {
                            table.ajax.reload();
                        } else {
                            showAlert(result.statusText, result.message, 'error');
                        }
                    })
                    .fail(function(jqXHR) {
                        showAlert(jqXHR.status, 'Request failed.', 'error');
                    });
            });
        });
    });
</script>
<?= $this->endSection() ?>
