<?= $this->extend("layout/master-profile") ?>
<?= $this->section("head_tag") ?>
<style>
    .progress-report-page {
        position: relative;
        min-height: 220px;
    }

    .page-loader-overlay {
        position: absolute;
        inset: 0;
        z-index: 10;
        background: rgba(255, 255, 255, 0.75);
        display: none;
        align-items: center;
        justify-content: center;
    }
</style>
<?= $this->endSection() ?>

<?= $this->section("page_content") ?>
<div class="mx-n3 pt-2 px-2 progress-report-page">
    <div id="page_loader_overlay" class="page-loader-overlay">
        <div class="spinner-border text-primary" role="status" aria-hidden="true"></div>
    </div>
    <div class="table-responsive">
        <table id="progress_report_datatable" class="table table-bordered align-middle nowrap" style="width:100%">
            <thead>
                <tr>
                    <th>Report ID</th>
                    <th>Period From</th>
                    <th>Period To</th>
                    <th>Version</th>
                    <th>Status</th>
                    <th>Created At</th>
                    <th>Updated At</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>
<?= $this->endSection() ?>

<?= $this->section("page_modal") ?>
<div class="modal fade" id="versions_modal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-header bg-light p-3">
                <h5 class="modal-title" id="versions_modal_title">Report Versions</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="table-responsive">
                    <table class="table table-bordered align-middle" id="versions_table">
                        <thead>
                            <tr>
                                <th>Version</th>
                                <th>Status</th>
                                <th>Generated At</th>
                                <th>Generated By</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><i class="ri-close-line align-bottom me-1"></i>Close</button>
            </div>
        </div>
    </div>
</div>
<?= $this->endSection() ?>

<?= $this->section("page_js") ?>
<script>
    $(document).ready(function() {
        var csrfToken = "<?= csrf_hash() ?>";
        var encodedClientId = "<?= esc($encodedClientId ?? '', 'js') ?>";
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': csrfToken
            }
        });

        function showPageLoader() {
            $('#page_loader_overlay').css('display', 'flex');
        }

        function hidePageLoader() {
            $('#page_loader_overlay').hide();
        }

        function buildPdfUrl(versionId) {
            return '<?= base_url('client-profile/reports/progress/version') ?>/' + encodedClientId + '/' + versionId + '/pdf';
        }

        function postWithLoader(url, payload) {
            showPageLoader();
            return $.post(url, payload).always(function() {
                hidePageLoader();
            });
        }

        var table = $('#progress_report_datatable').DataTable({
            ajax: {
                url: '<?= base_url('client-profile/reports/progress/data') ?>/' + encodedClientId,
                type: 'POST',
                beforeSend: function() {
                    showPageLoader();
                },
                complete: function() {
                    hidePageLoader();
                },
                error: function() {
                    hidePageLoader();
                },
                dataSrc: function(json) {
                    return (json && json.data) ? json.data : [];
                }
            },
            lengthChange: false,
            layout: {
                topStart: {
                    buttons: [{
                            extend: 'pageLength',
                            className: 'btn btn-light bg-gradient waves-effect waves-light'
                        },
                        {
                            extend: 'copy',
                            className: 'btn btn-light bg-gradient waves-effect waves-light'
                        },
                        {
                            extend: 'excel',
                            className: 'btn btn-light bg-gradient waves-effect waves-light'
                        },
                        {
                            extend: 'colvis',
                            className: 'btn btn-light bg-gradient waves-effect waves-light'
                        }
                    ]
                },
                topEnd: {
                    search: {
                        placeholder: 'Search'
                    }
                }
            },
            order: [
                [1, 'desc']
            ],
            columns: [{
                    data: 'report_id'
                },
                {
                    data: 'period_from',
                    render: function(data, type, row) {
                        if (!data) return '';
                        if (type === 'sort' || type === 'type') {
                            return moment(data, 'YYYY-MM-DD').format('YYYYMMDD');
                        }
                        return row.period_from_display || moment(data, 'YYYY-MM-DD').format(momentDateFormat);
                    }
                },
                {
                    data: 'period_to',
                    render: function(data, type, row) {
                        if (!data) return '';
                        if (type === 'sort' || type === 'type') {
                            return moment(data, 'YYYY-MM-DD').format('YYYYMMDD');
                        }
                        return row.period_to_display || moment(data, 'YYYY-MM-DD').format(momentDateFormat);
                    }
                },
                {
                    data: null,
                    render: function(data, type, row) {
                        return row.latest_version_id ? ('v' + row.latest_version_no) : '-';
                    }
                },
                {
                    data: 'latest_status',
                    render: function(data) {
                        if (String(data || '').toUpperCase() === 'FINAL') {
                            return '<span class="badge bg-success-subtle text-success text-uppercase">Final</span>';
                        }
                        return '<span class="badge bg-secondary-subtle text-secondary text-uppercase">N/A</span>';
                    }
                },
                {
                    data: 'created_at',
                    defaultContent: '',
                    render: function(data, type, row) {
                        if (!data) return '';
                        if (type === 'sort' || type === 'type') {
                            return moment(data).format('YYYYMMDDHHmmss');
                        }
                        return row.created_at_display || moment(data).format(momentDateFormat + ' HH:mm:ss');
                    }
                },
                {
                    data: 'updated_at',
                    defaultContent: '',
                    render: function(data, type, row) {
                        if (!data) return '';
                        if (type === 'sort' || type === 'type') {
                            return moment(data).format('YYYYMMDDHHmmss');
                        }
                        return row.updated_at_display || moment(data).format(momentDateFormat + ' HH:mm:ss');
                    }
                },
                {
                    data: null,
                    orderable: false,
                    render: function(data, type, row) {
                        var menu = '<div class="dropdown d-inline-block float-end">';
                        menu += '<a class="btn btn-soft-secondary btn-sm" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="ri-settings-3-fill align-middle"></i></a>';
                        menu += '<ul class="dropdown-menu dropdown-menu-end">';

                        if (row.report_id) {
                            var periodLabel = (row.period_from_display || row.period_from || '') + ' to ' + (row.period_to_display || row.period_to || '');
                            menu += '<li><a class="dropdown-item versions" href="#" data-report-id="' + row.report_id + '" data-period-label="' + periodLabel + '"><i class="ri-history-line align-bottom me-2 text-muted"></i>View Versions</a></li>';
                        }

                        if (row.latest_version_id) {
                            menu += '<li><a class="dropdown-item" target="_blank" href="' + buildPdfUrl(row.latest_version_id) + '"><i class="ri-file-pdf-line align-bottom me-2 text-muted"></i>View Latest PDF</a></li>';
                        }

                        menu += '</ul></div>';
                        return menu;
                    }
                }
            ]
        });

        $('#progress_report_datatable').on('click', '.versions', function(e) {
            e.preventDefault();
            var reportId = $(this).data('report-id');
            var periodLabel = $(this).data('period-label') || '';
            $('#versions_modal_title').text('Report Versions [' + periodLabel + ']');

            postWithLoader('<?= base_url('client-profile/reports/progress/versions') ?>/' + encodedClientId, {
                    report_id: reportId
                })
                .done(function(response) {
                    if (response.status !== 'success') {
                        showAlert(response.statusText, response.message, response.status);
                        return;
                    }

                    var rows = response.data || [];
                    var html = '';
                    rows.forEach(function(row) {
                        var viewBtn = row.version_id
                            ? '<a target="_blank" class="btn btn-sm btn-light" href="' + buildPdfUrl(row.version_id) + '">View PDF</a>'
                            : '<button class="btn btn-sm btn-light" disabled>No PDF</button>';

                        html += '<tr>' +
                            '<td>v' + row.version_no + '</td>' +
                            '<td>' + (row.status || 'FINAL') + '</td>' +
                            '<td>' + (row.generated_at_display || row.generated_at || '') + '</td>' +
                            '<td>' + (row.generated_by_name || '-') + '</td>' +
                            '<td>' + viewBtn + '</td>' +
                            '</tr>';
                    });

                    if (html === '') {
                        html = '<tr><td colspan="5" class="text-center">No final versions found.</td></tr>';
                    }

                    $('#versions_table tbody').html(html);
                    $('#versions_modal').modal('show');
                })
                .fail(function(jqXHR, textStatus, error) {
                    showAlert(jqXHR.status, 'Request failed: ' + textStatus + '<br>' + error, 'error');
                });
        });
    });
</script>
<?= $this->endSection() ?>
